### PR TITLE
Remove 'fs' dependency

### PR DESCRIPTION
**Pull request by pdehaan**
Ref: https://www.npmjs.com/package/fs

### CODE REVIEW

**Comment by pbelyaev** [comment]
@pdehaan Thanks for contributing.

**Comment by pdehaan** [comment]
Not sure that you need `path` either: https://github.com/pbelyaev/laravel-blade-parser/blob/master/package.json#L22

**Comment by pbelyaev** [comment]
@pdehaan thanks again, you are awesome! This is one of my first NPM packages so I could make some mistakes.

**Comment by pdehaan** [comment]
> This is one of my first NPM packages so I could make some mistakes.

Welcome to the wonderful world of Node.js and npm!

**Pull request merged**
